version: "3.9"

services:

  db:
    container_name: product_db
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    restart: on-failure

volumes:
  postgres_data:
