# Generated by Django 4.2.1 on 2023-06-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_creator_alter_product_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='hash',
            field=models.CharField(default='null', max_length=32),
            preserve_default=False,
        ),
    ]
