# Generated by Django 4.2.1 on 2023-06-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_imageremote_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productremote',
            name='creator',
        ),
    ]
